indonesian_names = [
    "Aditya", "Aisyah", "Amanda", "Andini", "Anggun", "Anggita", "Annisa", "Ariana", "Ashari",
    "Abimana", "Abimata", "Abirama", "Abiresa", "Adeline", "Adhitya", "Adiarja", "Adibrata", "Adikara",
    "Adinata", "Aditama", "Adriana", "Adwinta", "Agastya", "Aghania", "Agnesia", "Agustina", "Ahimsa",
    "Ainiyah", "Airlangga", "Aisyiah", "Ajendra", "Ajengan", "Akasaka", "Alamanda", "Alandra", "Aldebaran",
    "Aleandra", "Alethea", "Alexandra", "Alfiana", "Alindra", "Almaira", "Almeira", "Almyra", "Alodya",
    "Aloysius", "Alphanya", "Althafun", "Alviana", "Alyshia", "Amadeus", "Amandita", "Amartha", "Amartya",
    "Amelia", "Amelina", "Anargya", "Anastasia", "Andara", "Andhika", "Andika", "Andreana", "Angelica",
    "Angelina", "Angelia", "Anindita", "Anindya", "Anjani", "Annora", "Antaresa", "Anthonia", "Aprilia",
    "Arahita", "Arandea", "Ardhana", "Ardiana", "Arentha", "Ariadne", "Arianti", "Arifina", "Arimbi",
    "Arjuna", "Arkana", "Armadea", "Armina", "Arnetta", "Arsyifa", "Artemia", "Arthana", "Arundati",
    "Arvania", "Asadela", "Ashanty", "Ashilla", "Askara", "Asmarani", "Asmara", "Asteria", "Asterina",
    "Astinia", "Aswarini", "Athalia", "Athallah", "Athaya", "Athenia", "Athifah", "Athirah", "Atmaja",
    "Audhina", "Audrey", "Aurelia", "Aurellia", "Aurora", "Avalina", "Avantika", "Averina", "Avicenna",
    "Ayesha", "Ayudya", "Azalea", "Azalia", "Azarine", "Azkiya", "Azriel", "Azzahra", "Azzura",
    "Bagaskoro", "Bagawanta", "Baghiza", "Bahagia", "Bahtera", "Baktiar", "Balqies", "Balqis", "Bambang",
    "Banendra", "Barata", "Baruna", "Basudewa", "Batara", "Bathara", "Bayuaji", "Bayuwangi", "Belinda",
    "Beningati", "Bentara", "Berlianna", "Berliani", "Bernadin", "Bethari", "Betharia", "Bhadrika",
    "Bhanuwati", "Bhanuaji", "Bharata", "Bhirawa", "Bhisana", "Bhisma", "Bhumiaji", "Bhumika", "Bianda",
    "Biandra", "Bidadari", "Bidari", "Bijaya", "Binangkit", "Bintan", "Bintang", "Biruni", "Bramanta",
    "Bramanti", "Brawijaya", "Budiarta", "Budiman", "Budianto", "Bulandari", "Burhani", "Busaina",
    "Cakrawala", "Cakrayuda", "Calista", "Callysta", "Camelia", "Candida", "Candrika", "Carissa",
    "Carmelia", "Carolina", "Cassandra", "Catharina", "Cattleya", "Cempaka", "Chandani", "Chandra",
    "Chandrika", "Charissa", "Chelsea", "Chesilia", "Chiara", "Chintami", "Chintana", "Chintya",
    "Chrysant", "Chrysanta", "Cinthya", "Citrawati", "Clarissa", "Claudia", "Cordelia", "Cornelia",
    "Yustisia", "Zabrina", "Zafirah", "Zahirah", "Zalikha", "Zamira", "Zaneta", "Zanitha", "Zavira",
    "Zelinda", "Zenitha", "Zerlina", "Zharifa", "Zhafira", "Zhalfa", "Zhafirah", "Zhafarina", "Zhevania",
    "Zivanna", "Zulaikha", "Zulayha", "Zuleyka", "Zulfikar", "Zulhijah", "Zumaira", "Zumarni", "Zuwaina"
] 